### ISSUE TITLE
Google plus login not working

### ISSUE THREAD

**Issue by pluckq** [SimplicityMobile/Simplicity#21] opened 2016-09-27 08:42 UTC
I guess it happen coz google close it?
swift 3 ios 10

**Comment by edjiang** [comment] 2016-09-27 16:16
Can you please give me more details?

**Comment by pluckq** [comment] 2016-09-27 16:41
Hello, i just trying google login, but safari vc is not showing on, i watched with debuger, method called. Facebook working ok. I've just read about google closing some services api's, and think that's a problem?

**Comment by edjiang** [comment] 2016-09-27 18:31
Unfortunately I'm a bit busy over the next few days, so I don't have time to try to reproduce myself. However, if you can provide some screenshots or error messages, I can definitely help out!

**Comment by edjiang** [comment] 2016-11-17 21:29
Closing due to lack of detail. @pluckq feel free to chime in

**Closed by edjiang** 2016-11-17 21:29 UTC
